<a href="https://colab.research.google.com/github/cobase2010/mit-6.0036/blob/main/MIT6_036_hw06_colab_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MIT 6.036 Spring 2019: Homework 6

This homework does not include provided Python code. Instead, we encourage you to write your own code to help you answer some of these problems, and/or test and debug the code components we do ask for. All of the problems should be simple enough that hand calculation should be possible, but it may be convenient to write some short programs to explore the neural networks, particularly for problem 2.


In [33]:
import numpy as np
def relu(x):
  return np.maximum(x, 0)

def SM(z):
  # implement softmax
  return np.exp(z) / sum(np.exp(z))

def nll(a, y):
  return -1 * y @ np.log(a)

def nll_d(a, x, y):
  return x @ (a - y).T

 **Problem 2A**

In [ ]:
z = np.array([[-1, 0, 1]]).T
# your code here
a = SM(z)
print(a)

Problem 2B

In [12]:
a = np.array([.3, .5, .2]).T
y = np.array([0, 0, 1]).T
print(nll(a, y))

1.6094379124341003


**Problem 2.C-F**

In [24]:
w = np.array([[1, -1, -2], [-1, 2, 1]])
x = np.array([[1], [1]])
y = np.array([[0, 1, 0]]).T
# your code here
a = SM(w.T @ x)  # a: 3x1 
print(a)
print(nll_d(a, x, y))

w1 = w - 0.5 * nll_d(a, x, y)
print(w1)
a1 = SM(w1.T @ x)
print(a1)


[[0.24472847]
 [0.66524096]
 [0.09003057]]
[[ 0.24472847 -0.33475904  0.09003057]
 [ 0.24472847 -0.33475904  0.09003057]]
[[ 0.87763576 -0.83262048 -2.04501529]
 [-1.12236424  2.16737952  0.95498471]]
[[0.15918761]
 [0.77245284]
 [0.06835955]]


**Problem 3**

In [36]:
# layer 1 weights
w_1 = np.array([[1, 0, -1, 0], [0, 1, 0, -1]])
w_1_bias = np.array([[-1, -1, -1, -1]]).T
# layer 2 weights
w_2 = np.array([[1, -1], [1, -1], [1, -1], [1, -1]])
w_2_bias = np.array([[0, 2]]).T


# your code here
x = np.array([[3, 14]]).T
z1 = w_1.T @ x + w_1_bias
print(z1)
a1 = relu(z1)
print(a1)
z2 = w_2.T @ a1 + w_2_bias
a2 = SM(z2)
print(a2)


[[  2]
 [ 13]
 [ -4]
 [-15]]
[[ 2]
 [13]
 [ 0]
 [ 0]]
[[1.00000000e+00]
 [6.91440011e-13]]


In [39]:
x = np.array([[0.5, 0, -3], [0.5, 2, 0.5]])
z1 = w_1.T @ x + w_1_bias
print(z1)
a1 = relu(z1)
print(a1)

[[-0.5 -1.  -4. ]
 [-0.5  1.  -0.5]
 [-1.5 -1.   2. ]
 [-1.5 -3.  -1.5]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 2.]
 [0. 0. 0.]]


In [1]:
import numpy as np

T  = np.matrix([[0.0 , 0.1 , 0.9 , 0.0],
[0.9 , 0.1 , 0.0 , 0.0],
[0.0 , 0.0 , 0.1 , 0.9],
[0.9 , 0.0 , 0.0 , 0.1]])
g = 0.9
r = np.matrix([0, 1., 0., 2.]).reshape(4, 1)

print(np.linalg.solve(np.eye(4) - g * T, r))

[[6.05288295]
 [6.48663207]
 [6.7519581 ]
 [7.58553317]]
