In [63]:
import numpy as np

def one_hot(x, k):
    res = np.zeros((k, 1))
    res[x-1,:] = 1
    return res
# x = np.array([1, -1, 0, 1, -1.5, -1]).reshape(3, 2)
# x = np.array([1, -1, 0, 1, -10, -1]).reshape(3, 2)
# x = np.array([-3, 2, -1, 1, -1, -1, 2, 2, 1, -1]).reshape(5, 2)
# x = np.array([0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,1,0,1,1,1,0,1,1,1] ).reshape(8, 3)
# x = np.array([1, 2, 3, 4, 5, 6]).reshape(1, 6)
x = np.array(one_hot(1, 6))
x = np.append(x, one_hot(2, 6), 1)
x = np.append(x, one_hot(3, 6), 1)
x = np.append(x, one_hot(4, 6), 1)
x = np.append(x, one_hot(5, 6), 1)
x = np.append(x, one_hot(6, 6), 1)
x = x.reshape(6, 6)

print (x)
y = np.array([-1, 1, -1, 1, -1, 1]).reshape(1, 6)
print(y)
# Trying 0.5 * x transformation
# x = abs(x)
# x = x ** 4
# x = x ** (2*3)
# x2 = x ** 2
# x = np.append(x, x2, 0)     # using (x, x2) transformation


th = np.zeros((6, 1))
th0 = np.zeros((1, 1))
# theta_0 = np.array(1).reshape(1)
# theta = np.array([0, 0, -1]).reshape(3, 1)
# 
mistakes = 0
seperatable = True

for t in range(100):
    for i in range(6):
        y_i = y[0,i]  # taking ith label, should be scaler
        x_i = x[:,i]    # taking ith data column, should be d x 1 column vector

        if y_i * (th.T @ x_i + th0) <= 0:
            mistakes += 1
            if t == 99:
                seperatable = False
            th[:,0] = th[:,0] + y_i * x_i
            th0 = th0 + y_i  
print("Seperatable", seperatable)    
print("after", mistakes, "mistakes")
print("th", th)
print("th0", th0)

# nokia = np.array(one_hot(1, 6))
# nokia = np.append(nokia, one_hot(6, 6), 1)
# nokia = nokia.reshape(6, 2)

# result = np.sign(th.T @ nokia + th0)
# print(result)

# y = np.array([-1, -1]).reshape(1, 2)
# x = nokia
# for i in range(2):
#     y_i = y[0, i]
#     x_i = x[:,i]
#     print("x",i, linalg.norm(x_i))

#     gamma = y_i * (th.T @ x_i) / linalg.norm(th)
#     print("distance", gamma)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[-1  1 -1  1 -1  1]]
Seperatable True
after 6 mistakes
th [[-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]]
th0 [[0.]]


In [ ]:
import numpy as np
import numpy.linalg as linalg
# x = np.array([1, -1, 0, 1, -1.5, -1]).reshape(3, 2)
# x = np.array([1, -1, 0, 1, -10, -1]).reshape(3, 2)
# x = np.array([-3, 2, -1, 1, -1, -1, 2, 2, 1, -1]).reshape(5, 2)
# x = np.array([0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,1,0,1,1,1,0,1,1,1] ).reshape(8, 3)
x = np.array([[200, 800, 200, 800],
             [0.2,  0.2,  0.8,  0.8]])
x.reshape(2, 4)
x[0,:] = x[0,:] * 0.001
# x = np.array([-1, 0, 1]).reshape(1, 3)
# print(x)
y = np.array([-1, -1, 1, 1]).reshape(1, 4)
# print(y)
# Trying 0.5 * x transformation
# x = abs(x)
# x = x ** 4
# x = x ** (2*3)
# x2 = x ** 2
x = np.append(x, [[1, 1, 1, 1]], 0)     # using (x, x2) transformation
print(x)

th = np.zeros((3, 1))
# th = np.array([0, 1, -0.5]).reshape((3, 1))
# th0 = np.zeros((1, 1))
# theta_0 = np.array(1).reshape(1)
# theta = np.array([0, 0, -1]).reshape(3, 1)
# 
mistakes = 0
seperatable = True

margin = 1000
for i in range(4):
    y_i = y[0, i]
    x_i = x[:,i]
    print("x",i, linalg.norm(x_i))

    gamma = y_i * (th.T @ x_i) / linalg.norm(th)
    if gamma < margin:
        margin = gamma
print("margin", margin)
R = 1
print(800 * 0.001)
print("mistakes", (R/margin)**2)

print((1.5/0.268)**2)

for t in range(100):
    for i in range(4):
        y_i = y[0,i]  # taking ith label, should be scaler
        x_i = x[:,i]    # taking ith data column, should be d x 1 column vector

        if y_i * (th.T @ x_i) <= 0:
            mistakes += 1
            if t == 9999:
                seperatable = False
            th[:,0] = th[:,0] + y_i * x_i
            # th0 = th0 + y_i  
print("Seperatable", seperatable)    
print("after", mistakes, "mistakes")
print("th", th)
print("th0", th0)

Code for Excercise 4

In [10]:
import numpy as np
import numpy.linalg as linalg

def compute_margin(data, labels, th, th0):
    
    n = data.shape[1]
    min_res = np.inf
    max_res = -np.inf
    sum_res = 0
    for i in range(n):
        y_i = labels[0, i]
        x_i = data[:,i]
        # print("x",i, linalg.norm(x_i))

        margin = y_i * (th.T @ x_i + th0) / linalg.norm(th)
        if margin < min_res:
            min_res = margin
        if margin > max_res:
            max_res = margin
        sum_res += margin
        print(margin)

    return (min_res, max_res, sum_res)


Week4 Homework 1) Margin

In [9]:
data = np.array([[1, 2, 1, 2, 10, 10.3, 10.5, 10.7],
                 [1, 1, 2, 2,  2,  2,  2, 2]])
labels = np.array([[-1, -1, 1, 1, 1, 1, 1, 1]])
blue_th = np.array([[0, 1]]).T
blue_th0 = -1.5
red_th = np.array([[1, 0]]).T
red_th0 = -2.5

print(compute_margin(data, labels, red_th, red_th0))
print(compute_margin(data, labels, blue_th, blue_th0))


(array([-1.5]), array([8.2]), array([31.5]))
(array([0.5]), array([0.5]), array([4.]))


In [13]:
data = np.array([[1.1, 1, 4],[3.1, 1, 2]])
labels = np.array([[1, -1, -1]])
th = np.array([[1, 1]]).T
th0 = -4

compute_margin(data, labels, th, th0)
margins = [0.14142136, 1.41421356, -1.41421356]
r_ref = 2 ** 0.5 / 2
hinge_loss = []
for m in margins:
    if m  < r_ref:
        hinge_loss.append(1 - m / r_ref)
    else: 
        hinge_loss.append(0)
print(hinge_loss)


[0.14142136]
[1.41421356]
[-1.41421356]
[0.7999999946787522, 0, 2.999999996643937]


Excercise 5

In [ ]:
# Ex2.2
X = np.array([1, 3, 1, 1, 3, 2, 3, 6]).reshape(4, 2).T
print(X)
# for i in range(4):
#     print("(", -2 * (X[1,i] - X[0, i]) * X[0, i], ",", -2 * (X[1,i] - X[0, i]), ")")
# Ex2.3-2.4
for i in range(4):
    print((X[1, i] - X[0, i] - 1)**2)
    print("(", -2 * (X[1,i] - X[0, i] - 1) * X[0, i], ",", -2 * (X[1,i] - X[0, i] - 1), ")")



In [ ]:
X = np.array([[1, 2], [2, 3], [3, 5], [1, 4]])
print(X @ X.T)
np.linalg.inv(X @ X.T)