In [63]:
import numpy as np

def one_hot(x, k):
    res = np.zeros((k, 1))
    res[x-1,:] = 1
    return res
# x = np.array([1, -1, 0, 1, -1.5, -1]).reshape(3, 2)
# x = np.array([1, -1, 0, 1, -10, -1]).reshape(3, 2)
# x = np.array([-3, 2, -1, 1, -1, -1, 2, 2, 1, -1]).reshape(5, 2)
# x = np.array([0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,1,0,1,1,1,0,1,1,1] ).reshape(8, 3)
# x = np.array([1, 2, 3, 4, 5, 6]).reshape(1, 6)
x = np.array(one_hot(1, 6))
x = np.append(x, one_hot(2, 6), 1)
x = np.append(x, one_hot(3, 6), 1)
x = np.append(x, one_hot(4, 6), 1)
x = np.append(x, one_hot(5, 6), 1)
x = np.append(x, one_hot(6, 6), 1)
x = x.reshape(6, 6)

print (x)
y = np.array([-1, 1, -1, 1, -1, 1]).reshape(1, 6)
print(y)
# Trying 0.5 * x transformation
# x = abs(x)
# x = x ** 4
# x = x ** (2*3)
# x2 = x ** 2
# x = np.append(x, x2, 0)     # using (x, x2) transformation


th = np.zeros((6, 1))
th0 = np.zeros((1, 1))
# theta_0 = np.array(1).reshape(1)
# theta = np.array([0, 0, -1]).reshape(3, 1)
# 
mistakes = 0
seperatable = True

for t in range(100):
    for i in range(6):
        y_i = y[0,i]  # taking ith label, should be scaler
        x_i = x[:,i]    # taking ith data column, should be d x 1 column vector

        if y_i * (th.T @ x_i + th0) <= 0:
            mistakes += 1
            if t == 99:
                seperatable = False
            th[:,0] = th[:,0] + y_i * x_i
            th0 = th0 + y_i  
print("Seperatable", seperatable)    
print("after", mistakes, "mistakes")
print("th", th)
print("th0", th0)

# nokia = np.array(one_hot(1, 6))
# nokia = np.append(nokia, one_hot(6, 6), 1)
# nokia = nokia.reshape(6, 2)

# result = np.sign(th.T @ nokia + th0)
# print(result)

# y = np.array([-1, -1]).reshape(1, 2)
# x = nokia
# for i in range(2):
#     y_i = y[0, i]
#     x_i = x[:,i]
#     print("x",i, linalg.norm(x_i))

#     gamma = y_i * (th.T @ x_i) / linalg.norm(th)
#     print("distance", gamma)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[-1  1 -1  1 -1  1]]
Seperatable True
after 6 mistakes
th [[-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]]
th0 [[0.]]


In [43]:
import numpy as np
import numpy.linalg as linalg
# x = np.array([1, -1, 0, 1, -1.5, -1]).reshape(3, 2)
# x = np.array([1, -1, 0, 1, -10, -1]).reshape(3, 2)
# x = np.array([-3, 2, -1, 1, -1, -1, 2, 2, 1, -1]).reshape(5, 2)
# x = np.array([0,0,0,0,0,1,0,1,0,0,1,1,1,0,0,1,0,1,1,1,0,1,1,1] ).reshape(8, 3)
x = np.array([[200, 800, 200, 800],
             [0.2,  0.2,  0.8,  0.8]])
x.reshape(2, 4)
x[0,:] = x[0,:] * 0.001
# x = np.array([-1, 0, 1]).reshape(1, 3)
# print(x)
y = np.array([-1, -1, 1, 1]).reshape(1, 4)
# print(y)
# Trying 0.5 * x transformation
# x = abs(x)
# x = x ** 4
# x = x ** (2*3)
# x2 = x ** 2
x = np.append(x, [[1, 1, 1, 1]], 0)     # using (x, x2) transformation
print(x)

th = np.zeros((3, 1))
# th = np.array([0, 1, -0.5]).reshape((3, 1))
# th0 = np.zeros((1, 1))
# theta_0 = np.array(1).reshape(1)
# theta = np.array([0, 0, -1]).reshape(3, 1)
# 
mistakes = 0
seperatable = True

margin = 1000
for i in range(4):
    y_i = y[0, i]
    x_i = x[:,i]
    print("x",i, linalg.norm(x_i))

    gamma = y_i * (th.T @ x_i) / linalg.norm(th)
    if gamma < margin:
        margin = gamma
print("margin", margin)
R = 1
print(800 * 0.001)
print("mistakes", (R/margin)**2)

print((1.5/0.268)**2)

for t in range(100):
    for i in range(4):
        y_i = y[0,i]  # taking ith label, should be scaler
        x_i = x[:,i]    # taking ith data column, should be d x 1 column vector

        if y_i * (th.T @ x_i) <= 0:
            mistakes += 1
            if t == 9999:
                seperatable = False
            th[:,0] = th[:,0] + y_i * x_i
            # th0 = th0 + y_i  
print("Seperatable", seperatable)    
print("after", mistakes, "mistakes")
print("th", th)
print("th0", th0)

[[0.2 0.8 0.2 0.8]
 [0.2 0.2 0.8 0.8]
 [1.  1.  1.  1. ]]
x 0 1.0392304845413265
x 1 1.2961481396815722
x 2 1.2961481396815722
x 3 1.50996688705415
margin 1000
0.8
mistakes 1e-06
31.326576074849633
Seperatable True
after 7 mistakes
th [[-0.2]
 [ 1.6]
 [-1. ]]
th0 [[0.]]


/var/folders/w_/ccywlkcn2rqbgfykk3cjbl0w0000gn/T/ipykernel_30770/2298617822.py:38: RuntimeWarning: invalid value encountered in true_divide
  gamma = y_i * (th.T @ x_i) / linalg.norm(th)
